spring:
  application:
    name: edge-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
          - Path=/auth-service/api/v1/auth/**

        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory-service/api/v1/**
          filters:
            - AuthPredicateFilter

        - id: order-service
          uri: lb://ORDERING-SERVICE
          predicates:
            - Path=/order-service/api/v1/**
          filters:
            - AuthPredicateFilter
        
        - id: reporting-servive
          uri: lb://REPORTING-SERVICE
          predicates:
            - Path=/reporting-service/api/v1/**
          filters:
            - AuthPredicateFilter

server:
  port: 8084

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka


application:
  security:
    jwt:
      secret-key: 1d51bb9ccf2dff371dc418794f08078d33cfd17880f78e833b8f605f5fa493cb325b62849c1015fa6e5eea450400f18319a067d61b94b37046add594504882d6
      expiration: 3600000 # one day