spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Charlyco/Wiser-consulting-config.git
          skip-ssl-validation: true
          clone-on-start: true
          username: Charlyco
          password: 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

server:
  port: 8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
